### PR TITLE
user feedback on approval request, enable/disable buttons

### LINKED ISSUE #175: Improve user feedback on approval requests and enable/disable button
We currently don't provide much details if things go wrong when pressing the enable/disable button or interacting with approval requests. 

We should notify users of errors and display some spinners when things are happening.

### PR DESCRIPTION
**Pull request by tiftran**
fixes #175

### CODE REVIEW

File: extension/content/components/recipes/details/ApprovalRequest.js [hunk 1]
```diff
@@ -30,31 +31,47 @@ export default function ApprovalRequest() {
...
-    );
-    dispatch({
-      data: {
-        ...data,
-        approval_request: updatedApprovalRequest,
-      },
-      type: ACTION_UPDATE_DATA,
-    });
+    try {
+      setButtonLoad(true);
```
Comment (rehandalal) [inline extension/content/components/recipes/details/ApprovalRequest.js]: nit: this should probably be outside the `try` block

File: extension/content/components/recipes/details/DetailsHeader.js [hunk 2]
```diff
@@ -22,6 +22,7 @@ export default function DetailsHeader() {
   } = useSelectedEnvironmentState();
   const history = useHistory();
   const normandyApi = useSelectedNormandyEnvironmentAPI();
+  const [buttonLoad, setButtonLoad] = React.useState(false);
```
Comment (rehandalal) [inline extension/content/components/recipes/details/DetailsHeader.js]: nit: i tend to prefer prefixing boolean variables with something like `is`/`was`/`has` etc.

so something like `isButtonLoading` and `setIsButtonLoading`.

File: extension/content/components/recipes/details/ApprovalRequest.js [hunk 3]
```diff
@@ -30,31 +31,47 @@ export default function ApprovalRequest() {
...
```
Comment (rehandalal) [inline extension/content/components/recipes/details/ApprovalRequest.js]: nit: move out of `try` block

File: extension/content/components/recipes/details/ApprovalRequest.js [hunk 4]
```diff
@@ -16,6 +16,7 @@ export default function ApprovalRequest() {
   const normandyApi = useSelectedNormandyEnvironmentAPI();
 
   const [comment, updateComment] = React.useState("");
+  const [buttonLoad, setButtonLoad] = React.useState(false);
```
Comment (rehandalal) [inline extension/content/components/recipes/details/ApprovalRequest.js]: similarly should be prefixed.

but i think we need two variables: `isApproving` and `isRejecting`.

File: extension/content/components/recipes/details/ApprovalRequest.js [hunk 5]
```diff
@@ -82,10 +99,19 @@ export default function ApprovalRequest() {
       </div>
       <div className="d-flex mt-2">
         <div className="flex-grow-1">
-          <Button color="green" onClick={handleClickApprove}>
+          <Button
+            color="green"
+            loading={buttonLoad}
```
Comment (rehandalal) [inline extension/content/components/recipes/details/ApprovalRequest.js]:
```js
  loading={isApproving}
  disabled={isApproving || isRejecting}
```

File: extension/content/components/recipes/details/ApprovalRequest.js [hunk 6]
```diff
@@ -82,10 +99,19 @@ export default function ApprovalRequest() {
...
+            onClick={handleClickApprove}
+          >
             Approve
           </Button>
-          <Button className="ml-1" color="red" onClick={handleClickReject}>
+          <Button
+            className="ml-1"
+            color="red"
+            loading={buttonLoad}
```
Comment (rehandalal) [inline extension/content/components/recipes/details/ApprovalRequest.js]:
```js
  loading={isRejecting}
  disabled={isApproving || isRejecting}
```

File: extension/content/components/recipes/details/DetailsHeader.js [hunk 7]
```diff
@@ -32,30 +33,54 @@ export default function DetailsHeader() {
...
-    const approvalRequest = await normandyApi.requestApproval(data.id);
-    dispatch({
-      data: {
-        ...data,
-        approval_request: approvalRequest,
-      },
-      type: ACTION_UPDATE_DATA,
-    });
+    try {
+      setButtonLoad(true);
```
Comment (rehandalal) [inline extension/content/components/recipes/details/DetailsHeader.js]: nit: move out of try block

File: extension/content/components/recipes/details/DetailsHeader.js [hunk 8]
```diff
@@ -32,30 +33,54 @@ export default function DetailsHeader() {
...
   };
 
   const handleEnableClick = async () => {
-    const updatedRecipe = await normandyApi.enableRecipe(data.recipe.id);
-    dispatch({
-      data: updatedRecipe.approved_revision,
-      type: ACTION_UPDATE_DATA,
-    });
+    try {
+      setButtonLoad(true);
```
Comment (rehandalal) [inline extension/content/components/recipes/details/DetailsHeader.js]: nit: move out of try block

File: extension/content/components/recipes/details/DetailsHeader.js [hunk 9]
```diff
@@ -32,30 +33,54 @@ export default function DetailsHeader() {
...
   };
 
   const handleDisableClick = async () => {
-    const updatedRecipe = await normandyApi.disableRecipe(data.recipe.id);
-    dispatch({
-      data: updatedRecipe.approved_revision,
-      type: ACTION_UPDATE_DATA,
-    });
+    try {
+      setButtonLoad(true);
```
Comment (rehandalal) [inline extension/content/components/recipes/details/DetailsHeader.js]: nit: move out of try block

**Review by rehandalal — CHANGES_REQUESTED** [review]
needs a little tweak but looks good!

**Review by rehandalal — APPROVED** [review]
thanks!!

bors r+
