### PR TITLE
Fix #404: fix press enter in address bar

### LINKED ISSUE #404: In-page address bar is not editable
The in-page address bar that lists `ext+normandy://` addresses should be editable. A user should be able to type into it and then press enter to navigate to that desired page, just as in the normal address bar.

### PR DESCRIPTION
**Pull request by leplatrem**
Fix #404

- code would crash if match pattern is `null`
- pattern wouldn't match `web+normandy://`

### CODE REVIEW

File: content/components/common/AppHeader.js [hunk 1]
```diff
@@ -72,8 +72,10 @@ function AddressBar() {
 
   const handleKeyPress = (ev) => {
     if (ev.key === "Enter") {
-      const addressMatch = address.match(/ext\+normandy:\/(.+?)$/);
```
Comment (mythmon) [inline content/components/common/AppHeader.js:75]: Oops, this is my fault. I searched for `ext+normandy`, but forgot that some cases might have it escaped like this.

**Review by mythmon — APPROVED** [review]
bors r+
